language: node_js
node_js:
- '0.11'
before_install:
- rvm install 2.2.2
before_script:
- npm install -g bower grunt-cli
- gem install sass
- bower install
services: mongodb
after_success:
  # Turn off warnings about SSH keys:
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  # Clear your current Heroku SSH keys:
  - heroku keys:clear
  # Add a new SSH key to Heroku
  - yes | heroku keys:add
  # Clone Heroku deployment repo to dist folder
  - mkdir dist
  # Build
  - git config --global user.name "Christian Stump"
  - git config --global user.email "christian.m.stump@gmail.com"
  - grunt build
  - grunt buildcontrol:herokuDev
  # Commit and Push dist folder to Heroku
  #  - cd dist
  #  - git config --global user.name "Christian Stump"
  #  - git config --global user.email "christian.m.stump@gmail.com"
  #  - git add *
  #  - git commit -am "Travis CI"
  #  - git push origin master
env:
  global:
    secure: cCRWXVVerlZO76ds1P2HJpSXIBF5fp1NXdKfjdiLbRz8xFqjkCERp0hVl6DQ0fuutSIyJelQxeNEy3iiDdeS4XYy1PMP8Wk6nBbbJvhq0CF0B1vnDSiRKCigsD6w7hDD5das0HhtJog6s+ZMawVJCc44yyyaGv1c6H4vc+u0ozBZKmGZwX9GM3pV58MLmHgwWSckAQpOk0nLEc83CdsFDZ41h6hKsR5KMR9nJFp7xE3k5P+vfHAdeWZQGz0xNMs9XvSLX3GLzZG8EjaNH/Kez7xYFoXhVKsYH7N2nfzO7DFdA/guTZq/Yl47qL39JbHDvpQ6kU024gJBQFf+UemYHixYOonLKSeH6LufyOV1uFfVr/p3sMN7tVxWk1ef7WknGFb77ByRHUimIldgGwGyOcfEGM92/1nWjum31E/4kAOvQYbXxziAj34wRUJp/h8pTFxuYpP9cKldprcJpKjgxt5ZgKITXFJfm9eQbdUkuI3Gr9irFVLhH3w7cF2MxaIIH2rr+WpGiw4Hq1e1r1lP1Aoi+VBH2eyYxYuTUJqHf8qTawRwzsEwaWWex6XRZJu5eHJkif0IUHyb38m9iIhLa8lfRmToFWeyTSU5r4rYuwaVhxaQQuYbGDrWeMxz+ZcSgTTGmeKqFPmaUUlOa1n1bIKgTEmuUpb4tLrw6ISpmjo=
#after_success:
#  bash ./travis/after_success.sh
#deploy:
#  provider: heroku
#  api_key:
#    secure: cCRWXVVerlZO76ds1P2HJpSXIBF5fp1NXdKfjdiLbRz8xFqjkCERp0hVl6DQ0fuutSIyJelQxeNEy3iiDdeS4XYy1PMP8Wk6nBbbJvhq0CF0B1vnDSiRKCigsD6w7hDD5das0HhtJog6s+ZMawVJCc44yyyaGv1c6H4vc+u0ozBZKmGZwX9GM3pV58MLmHgwWSckAQpOk0nLEc83CdsFDZ41h6hKsR5KMR9nJFp7xE3k5P+vfHAdeWZQGz0xNMs9XvSLX3GLzZG8EjaNH/Kez7xYFoXhVKsYH7N2nfzO7DFdA/guTZq/Yl47qL39JbHDvpQ6kU024gJBQFf+UemYHixYOonLKSeH6LufyOV1uFfVr/p3sMN7tVxWk1ef7WknGFb77ByRHUimIldgGwGyOcfEGM92/1nWjum31E/4kAOvQYbXxziAj34wRUJp/h8pTFxuYpP9cKldprcJpKjgxt5ZgKITXFJfm9eQbdUkuI3Gr9irFVLhH3w7cF2MxaIIH2rr+WpGiw4Hq1e1r1lP1Aoi+VBH2eyYxYuTUJqHf8qTawRwzsEwaWWex6XRZJu5eHJkif0IUHyb38m9iIhLa8lfRmToFWeyTSU5r4rYuwaVhxaQQuYbGDrWeMxz+ZcSgTTGmeKqFPmaUUlOa1n1bIKgTEmuUpb4tLrw6ISpmjo=
#  app:
#    development: ra-dev
#  run: "grunt serve"
  
